[package]
name = "bdk_electrum"
version = "0.15.0"
edition = "2021"
homepage = "https://bitcoindevkit.org"
repository = "https://github.com/bitcoindevkit/bdk"
documentation = "https://docs.rs/bdk_electrum"
description = "Fetch data from electrum in the form BDK accepts"
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Keeping the path here breaks the build when using the fork as a dependency #135 has the first line instead but for building
# the bindings we need the second line
# bdk_chain = { path = "../chain", version = "0.16.0" }
bdk_chain = { version = "0.16.0" }

# Switch the lines below once https://github.com/bitcoindevkit/rust-electrum-client/pull/135 is merged and a new version is released
# electrum-client = { version = "0.21", default-features = false }
electrum-client = { git = "https://github.com/thunderbiscuit/rust-electrum-client/", branch = "feature/rustls-ring", default-features = false }

[dev-dependencies]
bdk_testenv = { path = "../testenv", default-features = false }

[features]
default = ["use-rustls"]
use-rustls = ["electrum-client/proxy", "electrum-client/use-rustls"]
use-rustls-ring = ["electrum-client/use-rustls-ring"]
